//! A store written by Ultra Edit 0.3.0 must keep working byte for byte. Receipts
//! are found by digesting a plan's re-serialized bytes, and immutable objects are
//! compared by value on every idempotent write, so any change in how a persisted type
//! serializes would turn old receipts into `JOURNAL_CORRUPT` and old requests into
//! `OBJECT_CONFLICT`. The fixture in `tests/fixtures/store-0.3.0` was generated by the
//! 0.3.0 code (see `generate.rs` there) and must never be regenerated by later code.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::Duration;

use serde::Serialize;
use serde::de::DeserializeOwned;
use serde_json::{Value, json};
use tempfile::TempDir;
use ultra_edit::storage::Storage;
use ultra_edit::workspace::{EditResult, Evidence};
use ultra_edit::*;

/// The persisted object kinds with a public type, each checked for byte identity.
const TYPED_KINDS: [&str; 5] = [
    "snapshots",
    "plans",
    "drafts",
    "inspections",
    "reconciliations",
];

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/store-0.3.0")
}

fn manifest() -> Value {
    serde_json::from_slice(&fs::read(fixture().join("manifest.json")).unwrap()).unwrap()
}

fn request(name: &str) -> Value {
    manifest()["requests"][name].clone()
}

fn parse<T: DeserializeOwned>(value: &Value) -> T {
    serde_json::from_value(value.clone()).unwrap()
}

fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir_all(to).unwrap();
    for entry in fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let target = to.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            fs::copy(entry.path(), target).unwrap();
        }
    }
}

/// A workspace whose state directory is a copy of the fixture store.
fn copied() -> (TempDir, Workspace) {
    let root = TempDir::new().unwrap();
    copy_tree(&fixture().join("state"), &root.path().join(".ultra-edit"));
    let workspace = Workspace::open(root.path()).unwrap();
    (root, workspace)
}

fn object_ids(kind: &str) -> Vec<String> {
    let directory = fixture().join("state").join(kind);
    let mut ids: Vec<String> = fs::read_dir(directory)
        .unwrap()
        .map(|entry| {
            let path = entry.unwrap().path();
            assert_eq!(path.extension().unwrap(), "json", "{}", path.display());
            path.file_stem().unwrap().to_str().unwrap().to_owned()
        })
        .collect();
    ids.sort();
    ids
}

/// Loads one object as its type and checks that the type reproduces the stored value
/// and the 0.3.0 `to_vec` bytes, and that writing it again is idempotent and
/// recreates the stored file and blobs byte for byte in an empty store.
fn assert_round_trip<T: Serialize + DeserializeOwned>(
    stored: &Storage,
    fresh: &Storage,
    kind: &str,
    id: &str,
) {
    let value: Value = stored.get(kind, id).unwrap();
    let typed: T = stored.get(kind, id).unwrap();
    assert_eq!(serde_json::to_value(&typed).unwrap(), value, "{kind}/{id}");
    assert_eq!(
        Value::String(digest(&serde_json::to_vec(&typed).unwrap())),
        manifest()["objects"][format!("{kind}/{id}")],
        "{kind}/{id} to_vec bytes changed"
    );
    stored.put(kind, id, &typed).unwrap();
    fresh.put(kind, id, &typed).unwrap();
    let name = format!("{id}.json");
    assert_eq!(
        fs::read(fresh.root().join(".ultra-edit").join(kind).join(&name)).unwrap(),
        fs::read(fixture().join("state").join(kind).join(&name)).unwrap(),
        "{kind}/{id} file bytes changed"
    );
}

#[test]
fn every_0_3_0_object_loads_and_reserializes_byte_identically() {
    let (_root, workspace) = copied();
    let stored = Storage::open(workspace.root()).unwrap();
    let fresh_root = TempDir::new().unwrap();
    let fresh = Storage::open(fresh_root.path()).unwrap();
    let mut checked = 0;
    for kind in TYPED_KINDS {
        for id in object_ids(kind) {
            match kind {
                "snapshots" => assert_round_trip::<Snapshot>(&stored, &fresh, kind, &id),
                "plans" => assert_round_trip::<PreparedPlan>(&stored, &fresh, kind, &id),
                "drafts" => assert_round_trip::<Draft>(&stored, &fresh, kind, &id),
                "inspections" => assert_round_trip::<Inspection>(&stored, &fresh, kind, &id),
                _ => assert_round_trip::<Reconciliation>(&stored, &fresh, kind, &id),
            }
            checked += 1;
        }
    }
    assert_eq!(checked, manifest()["objects"].as_object().unwrap().len());
    // Every blob the fixture holds was recreated from the typed objects alone.
    let blobs = |root: &Path| {
        let mut blobs: Vec<(String, Vec<u8>)> = fs::read_dir(root.join("blobs"))
            .unwrap()
            .map(|entry| {
                let entry = entry.unwrap();
                let name = entry.file_name().into_string().unwrap();
                (name, fs::read(entry.path()).unwrap())
            })
            .collect();
        blobs.sort();
        blobs
    };
    let original = blobs(&fixture().join("state"));
    assert!(!original.is_empty(), "the fixture must exercise blobs");
    assert_eq!(blobs(&fresh_root.path().join(".ultra-edit")), original);

    // Request bindings have no public type; their edit requests and repair
    // corrections must still parse into the same values.
    let mut kinds = Vec::new();
    for id in object_ids("requests") {
        let binding: Value = stored.get("requests", &id).unwrap();
        let input = &binding["input"];
        kinds.push(input["kind"].as_str().unwrap().to_owned());
        match input["kind"].as_str().unwrap() {
            "edit" => assert_eq!(
                serde_json::to_value(parse::<EditRequest>(&input["request"])).unwrap(),
                input["request"]
            ),
            "repair" => assert_eq!(
                serde_json::to_value(parse::<Vec<Change>>(&input["changes"])).unwrap(),
                input["changes"]
            ),
            _ => {}
        }
        stored.put("requests", &id, &binding).unwrap();
    }
    kinds.sort();
    assert_eq!(kinds, ["edit", "edit", "edit", "edit", "repair", "undo"]);
}

#[test]
fn recorded_0_3_0_receipts_return_and_identical_requests_replay() {
    let (_root, workspace) = copied();
    for name in ["edit", "repair", "undo", "stale", "interrupted"] {
        let recorded = request(name);
        let receipt: Receipt = parse(&recorded["receipt"]);
        assert_eq!(
            workspace
                .receipt(recorded["request_id"].as_str().unwrap())
                .unwrap(),
            Some(receipt),
            "{name}"
        );
    }
    let rejected = request("rejected");
    assert_eq!(
        workspace
            .receipt(rejected["request_id"].as_str().unwrap())
            .unwrap(),
        None
    );

    // Derived IDs and bindings written by 0.3.0 still match identical arguments.
    let edit = request("edit");
    let EditResult::Completed {
        receipt, replayed, ..
    } = workspace.edit(parse(&edit["arguments"])).unwrap()
    else {
        panic!("Expected the recorded receipt")
    };
    assert!(replayed);
    assert_eq!(receipt, parse::<Receipt>(&edit["receipt"]));
    let EditResult::Rejected { preparation } =
        workspace.edit(parse(&rejected["arguments"])).unwrap()
    else {
        panic!("Expected the recorded draft")
    };
    assert!(preparation.replayed);
    assert_eq!(preparation.reference, rejected["draft"]);
    let repair = request("repair");
    let repaired = workspace
        .repair(
            repair["reference"].as_str().unwrap(),
            "",
            parse(&repair["changes"]),
        )
        .unwrap();
    assert!(repaired.replayed);
    assert_eq!(repaired.reference, repair["plan"]);
    assert_eq!(repaired.receipt, Some(parse(&repair["receipt"])));
    let undo = request("undo");
    let EditResult::Completed {
        receipt, replayed, ..
    } = workspace
        .undo(undo["reference"].as_str().unwrap(), "")
        .unwrap()
    else {
        panic!("Expected the recorded undo")
    };
    assert!(replayed);
    assert_eq!(receipt, parse::<Receipt>(&undo["receipt"]));
    let stale = request("stale");
    let (receipt, replayed) = workspace
        .commit_or_replay(stale["plan"].as_str().unwrap())
        .unwrap();
    assert!(replayed);
    assert_eq!(receipt.commit, CommitStatus::NotCommitted);

    // The reconciled interrupted commit keeps its uncertain receipt and blocks nothing.
    let interrupted = request("interrupted");
    let Evidence::Inspection(inspection) = workspace
        .evidence(interrupted["inspection"].as_str().unwrap())
        .unwrap()
    else {
        panic!("Expected the recorded inspection")
    };
    assert_eq!(
        inspection.receipt.unwrap().commit,
        CommitStatus::OutcomeUnknown
    );
    assert!(
        workspace
            .root()
            .join(".ultra-edit/uncertain")
            .join(interrupted["plan"].as_str().unwrap())
            .exists()
    );
    let pruning = workspace.prune_snapshots(Duration::ZERO, false).unwrap();
    assert!(pruning.dry_run);
    assert_eq!(pruning.removed_snapshots, 0);
    assert_eq!(pruning.reclaimable_blobs, 0);
}

/// Points the snapshots and the plan `plan_id` at files under `root` instead of the
/// generating machine's workspace, rewriting their checksums and the plan's journal
/// digest. Only the relocated plan's history is touched; everything else stays as
/// 0.3.0 wrote it.
fn relocate(workspace: &Workspace, plan_id: &str) {
    let from = manifest()["root"].as_str().unwrap().to_owned();
    let state = workspace.root().join(".ultra-edit");
    let rewrite = |path: &Path, payload: Value| {
        fs::write(path, record(&payload, false)).unwrap();
    };
    let paths = |value: &mut Value| relocate_paths(value, &from, workspace.root());
    for id in object_ids("snapshots") {
        let path = state.join("snapshots").join(format!("{id}.json"));
        let mut payload = payload(&fs::read(&path).unwrap());
        paths(&mut payload);
        rewrite(&path, payload);
    }
    let path = state.join("plans").join(format!("{plan_id}.json"));
    let mut plan = payload(&fs::read(&path).unwrap());
    paths(&mut plan);
    rewrite(&path, plan);
    let typed: PreparedPlan = Storage::open(workspace.root())
        .unwrap()
        .get("plans", plan_id)
        .unwrap();
    let journal = state.join("journals").join(format!("{plan_id}.jsonl"));
    let mut bytes = Vec::new();
    for line in fs::read(&journal)
        .unwrap()
        .split_inclusive(|byte| *byte == b'\n')
    {
        let mut event = payload(line);
        if event["event"] == "begin" {
            event["plan_digest"] = json!(digest(&serde_json::to_vec(&typed).unwrap()));
        }
        bytes.extend(record(&event, true));
    }
    fs::write(journal, bytes).unwrap();
}

fn relocate_paths(value: &mut Value, from: &str, root: &Path) {
    match value {
        Value::String(text) => {
            if let Some(rest) = text
                .strip_prefix(from)
                .and_then(|rest| rest.strip_prefix('/'))
            {
                let path = rest
                    .split('/')
                    .fold(root.to_path_buf(), |path, component| path.join(component));
                *text = path.to_str().unwrap().to_owned();
            }
        }
        Value::Array(items) => items
            .iter_mut()
            .for_each(|item| relocate_paths(item, from, root)),
        Value::Object(map) => map
            .values_mut()
            .for_each(|item| relocate_paths(item, from, root)),
        _ => {}
    }
}

fn payload(bytes: &[u8]) -> Value {
    let checked: Value = serde_json::from_slice(bytes).unwrap();
    checked["payload"].clone()
}

fn record(payload: &Value, line: bool) -> Vec<u8> {
    let checksum = digest(&serde_json::to_vec(payload).unwrap());
    let mut bytes = serde_json::to_vec(&json!({"checksum": checksum, "payload": payload})).unwrap();
    if line {
        bytes.push(b'\n');
    }
    bytes
}

#[test]
fn committed_0_3_0_plan_undoes_after_relocation_and_prunes() {
    let (_root, workspace) = copied();
    let edit = request("edit");
    let plan_id = edit["receipt"]["plan_id"].as_str().unwrap();
    relocate(&workspace, plan_id);
    let Evidence::Plan(plan) = workspace.evidence(plan_id).unwrap() else {
        panic!("Expected the committed plan")
    };
    for file in &plan.files {
        fs::write(&file.base.path, &file.output).unwrap();
    }
    assert_eq!(
        workspace
            .receipt(edit["request_id"].as_str().unwrap())
            .unwrap()
            .unwrap()
            .commit,
        CommitStatus::Committed
    );
    let EditResult::Completed {
        receipt, replayed, ..
    } = workspace.undo(plan_id, "undo-0.3.0-edit").unwrap()
    else {
        panic!("Expected the undo to commit")
    };
    assert!(!replayed);
    assert_eq!(receipt.commit, CommitStatus::Committed);
    for file in &plan.files {
        assert_eq!(fs::read_to_string(&file.base.path).unwrap(), file.base.text);
    }
    // Committing scanned the reconciled marker away; history remains intact.
    let interrupted = request("interrupted");
    assert!(
        !workspace
            .root()
            .join(".ultra-edit/uncertain")
            .join(interrupted["plan"].as_str().unwrap())
            .exists()
    );
    assert_eq!(
        workspace.receipt("interrupted-0.3.0").unwrap(),
        Some(parse(&interrupted["receipt"]))
    );
    let pruning = workspace.prune_snapshots(Duration::ZERO, false).unwrap();
    assert!(pruning.dry_run);
    let applied = workspace.prune_snapshots(Duration::ZERO, true).unwrap();
    assert_eq!(applied.removed_snapshots, pruning.eligible.len());
    for name in ["edit", "repair", "undo", "stale"] {
        let recorded = request(name);
        assert!(
            workspace
                .receipt(recorded["request_id"].as_str().unwrap())
                .unwrap()
                .is_some(),
            "{name}"
        );
    }
}
